hello:
  name: spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sandbox
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update #create-drop